# Generated by Django 5.0.3 on 2024-03-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_members_chatroom_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroomconnector',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
