# Generated by Django 5.0.2 on 2024-03-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='like',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike'), (0, 'No Reaction')], default=0),
        ),
    ]
